# Generated by Django 5.0.4 on 2024-04-24 00:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyflans_djweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='flan_uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(upload_to='media/img/productos'),
        ),
    ]
