# Generated by Django 5.0.4 on 2024-04-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyflans_djweb', '0002_remove_product_id_product_flan_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
