# Generated by Django 5.0.4 on 2024-04-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyflans_djweb', '0003_alter_product_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flan_uuid',
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
