# Generated by Django 5.0.4 on 2024-04-25 00:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyflans_djweb', '0004_remove_product_flan_uuid_alter_product_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flan_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
