# Generated by Django 5.0.4 on 2024-04-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyflans_djweb', '0005_product_flan_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
